spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.227.131:3306/mall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-order
  rabbitmq:
    host: 192.168.227.131
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated  # 开启确认模式：发布消息成功到交换器后会触发回调方法
    publisher-returns: true  # 开启发送端消息抵达队列的确认
    template:
      mandatory: true  # 只要抵达队列，以异步方式优先回调return确认
    listener:
      simple:
        acknowledge-mode: manual  # 开启手动确认模式，只要没有ACK，则消息一直是unacked状态，消费者宕机，消息重新变为ready状态
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.227.131
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9000

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

alipay:
  app_id: 2021000121687734
  merchant_private_key: [保密]
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlBzImtiLvTGCzjaHW7sbXQ48BShHLjDjuMm6fDmLtWFarvuKSxZ+Qtfr2qnOgEGe88sOuzpHqwRpj5sRGCPnoJgf6SL9SiXIiAzMOc1kaMAFkUC2bVUcl33H8Yj1MCdnWQeLDjq0i38Qe5vompxsywjszgXiWrZvl50V8nQB80WmVRqfudoCGuHUTLXVdI0SOTZoXQdRKmcBizTL5U1d6QgYT20a5UJssard4AJjLrEvTqToN2e4HRvVE8n+6L1utai6lrP+K56sZTGDdf22PtEwEcZsnG8AInO6/4VkgtV0F1Txv4iwKeRsu+8VCEhSStR0plNoYTLRitnB4UBgiQIDAQAB
  notify_url: http://localhost/payed/notify  # 应该使用外网地址，映射到order.mall.com
  return_url: http://member.mall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do